const ChannelIcons = {
    '24 ДОК': require('../assets/channels/24 ДОК.png'),
    '2X2': require('../assets/channels/2X2.png'),
    '5 канал (Украина)': require('../assets/channels/5 канал (Украина).png'),
    'AMC': require('../assets/channels/AMC.png'),
    'AMEDIA HIT': require('../assets/channels/AMEDIA HIT.png'),
    'ATV': require('../assets/channels/ATV.png'),
    'Amedia 1': require('../assets/channels/Amedia 1.png'),
    'Amedia 2': require('../assets/channels/Amedia 2.png'),
    'Amedia Premium HD': require('../assets/channels/Amedia Premium HD.png'),
    'Ani': require('../assets/channels/Ani.png'),
    'Animal Planet HD': require('../assets/channels/Animal Planet HD.png'),
    'Animal Planet': require('../assets/channels/Animal Planet.png'),
    'Ararat': require('../assets/channels/Ararat.png'),
    'BBC World News': require('../assets/channels/BBC World News.png'),
    'Bloomberg': require('../assets/channels/Bloomberg.png'),
    'Bridge TV': require('../assets/channels/Bridge TV.png'),
    'CBS Drama': require('../assets/channels/CBS Drama.png'),
    'CBS Reality': require('../assets/channels/CBS Reality.png'),
    'Cartoon Network': require('../assets/channels/Cartoon Network.png'),
    'DTX': require('../assets/channels/DTX.png'),
    'Discovery Channel HD': require('../assets/channels/Discovery Channel HD.png'),
    'Discovery Channel': require('../assets/channels/Discovery Channel.png'),
    'Discovery Science': require('../assets/channels/Discovery Science.png'),
    'Disney': require('../assets/channels/Disney.png'),
    'E!': require('../assets/channels/E!.png'),
    'Eurosport 1 HD': require('../assets/channels/Eurosport 1 HD.png'),
    'Eurosport 1': require('../assets/channels/Eurosport 1.png'),
    'Eurosport 2': require('../assets/channels/Eurosport 2.png'),
    'Extreme Sports': require('../assets/channels/Extreme Sports.png'),
    'Food Network': require('../assets/channels/Food Network.png'),
    'Fox HD': require('../assets/channels/Fox HD.png'),
    'Fox Life': require('../assets/channels/Fox Life.png'),
    'Fox Russia': require('../assets/channels/Fox Russia.png'),
    'Freeform': require('../assets/channels/Freeform.png'),
    'Gulli': require('../assets/channels/Gulli.png'),
    'HD Life': require('../assets/channels/HD Life.png'),
    'HTH': require('../assets/channels/HTH.png'),
    'History HD': require('../assets/channels/History HD.png'),
    'ID Xtra': require('../assets/channels/ID Xtra.png'),
    'Jim Jam': require('../assets/channels/Jim Jam.png'),
    'KHL': require('../assets/channels/KHL.png'),
    'Life News': require('../assets/channels/Life News.png'),
    'MGM HD': require('../assets/channels/MGM HD.png'),
    'MTV Dance': require('../assets/channels/MTV Dance.png'),
    'MTV Hits': require('../assets/channels/MTV Hits.png'),
    'MTV Live HD': require('../assets/channels/MTV Live HD.png'),
    'MTV.AM HD': require('../assets/channels/MTV.AM HD.png'),
    'MTV.AM': require('../assets/channels/MTV.AM.png'),
    'MTV': require('../assets/channels/MTV.png'),
    'Mezzo Live HD': require('../assets/channels/Mezzo Live HD.png'),
    'Mezzo': require('../assets/channels/Mezzo.png'),
    'Nat Geo Wild HD': require('../assets/channels/Nat Geo Wild HD.png'),
    'Nat Geo Wild': require('../assets/channels/Nat Geo Wild.png'),
    'National Geographic HD': require('../assets/channels/National Geographic HD.png'),
    'Nick Jr': require('../assets/channels/Nick Jr.png'),
    'Nickelodeon HD': require('../assets/channels/Nickelodeon HD.png'),
    'Nickelodeon': require('../assets/channels/Nickelodeon.png'),
    'OCEAN-TV': require('../assets/channels/OCEAN-TV.png'),
    'Outdoor Channel': require('../assets/channels/Outdoor Channel.png'),
    'PanArmenian': require('../assets/channels/PanArmenian.png'),
    'Paramount Comedy Russia': require('../assets/channels/Paramount Comedy Russia.png'),
    'Playboy': require('../assets/channels/Playboy.png'),
    'RTG HD': require('../assets/channels/RTG HD.png'),
    'RUSONG TV': require('../assets/channels/RUSONG TV.png'),
    'STV': require('../assets/channels/STV.png'),
    'Sony Entertainment Televi': require('../assets/channels/Sony Entertainment Television.png'),
    'Sony Sci-Fi': require('../assets/channels/Sony Sci-Fi.png'),
    'Sony Turbo': require('../assets/channels/Sony Turbo.png'),
    'TLC HD': require('../assets/channels/TLC HD.png'),
    'TV 1000 Action': require('../assets/channels/TV 1000 Action.png'),
    'TV 1000 Русское кино': require('../assets/channels/TV 1000 Русское кино.png'),
    'TV 1000': require('../assets/channels/TV 1000.png'),
    'TV XXI': require('../assets/channels/TV XXI.png'),
    'TV1000 Comedy HD': require('../assets/channels/TV1000 Comedy HD.png'),
    'TV1000 Megahit HD': require('../assets/channels/TV1000 Megahit HD.png'),
    'TV1000 Premium HD': require('../assets/channels/TV1000 Premium HD.png'),
    'Tiji TV': require('../assets/channels/Tiji TV.png'),
    'Toot': require('../assets/channels/Toot.png'),
    'Trace Sport Stars HD': require('../assets/channels/Trace Sport Stars HD.png'),
    'Trace Urban HD': require('../assets/channels/Trace Urban HD.png'),
    'Travel Channel HD': require('../assets/channels/Travel Channel HD.png'),
    'Travel Channel': require('../assets/channels/Travel Channel.png'),
    'VH1 European': require('../assets/channels/VH1 European.png'),
    'Viasat Explore': require('../assets/channels/Viasat Explore.png'),
    'Viasat History': require('../assets/channels/Viasat History.png'),
    'Viasat Nature-History HD': require('../assets/channels/Viasat Nature-History HD.png'),
    'Viasat Nature': require('../assets/channels/Viasat Nature.png'),
    'Viasat Sport HD': require('../assets/channels/Viasat Sport HD.png'),
    'Viasat Sport': require('../assets/channels/Viasat Sport.png'),
    'nat geographic': require('../assets/channels/nat geographic.png'),
    'Авто 24': require('../assets/channels/Авто 24.png'),
    'Авто Плюс': require('../assets/channels/Авто Плюс.png'),
    'Время': require('../assets/channels/Время.png'),
    'Детский мир': require('../assets/channels/Детский мир.png'),
    'Дом Кино': require('../assets/channels/Дом Кино.png'),
    'Домашние Животные': require('../assets/channels/Домашние Животные.png'),
    'Домашний': require('../assets/channels/Домашний.png'),
    'Еврокино': require('../assets/channels/Еврокино.png'),
    'Европа Плюс': require('../assets/channels/Европа Плюс.png'),
    'ИНДИЙСКОЕ КИНО': require('../assets/channels/ИНДИЙСКОЕ КИНО.png'),
    'Иллюзион +': require('../assets/channels/Иллюзион +.png'),
    'История': require('../assets/channels/История.png'),
    'КВН ТВ': require('../assets/channels/КВН ТВ.png'),
    'КИНОКОМЕДИЯ': require('../assets/channels/КИНОКОМЕДИЯ.png'),
    'КИНОМИКС': require('../assets/channels/КИНОМИКС.png'),
    'КИНОПРЕМЬЕРА HD': require('../assets/channels/КИНОПРЕМЬЕРА HD.png'),
    'КИНОСЕМЬЯ': require('../assets/channels/КИНОСЕМЬЯ.png'),
    'Карусель': require('../assets/channels/Карусель.png'),
    'Кинохит': require('../assets/channels/Кинохит.png'),
    'Конный Мир HD': require('../assets/channels/Конный Мир HD.png'),
    'Кухня ТВ': require('../assets/channels/Кухня ТВ.png'),
    'МУЖСКОЕ КИНО': require('../assets/channels/МУЖСКОЕ КИНО.png'),
    'МУЗ': require('../assets/channels/МУЗ.png'),
    'Мама': require('../assets/channels/Мама.png'),
    'Матч ТВ': require('../assets/channels/Матч ТВ.png'),
    'Матч! HD': require('../assets/channels/Матч! HD.png'),
    'Матч! Арена HD': require('../assets/channels/Матч! Арена HD.png'),
    'Матч! Арена': require('../assets/channels/Матч! Арена.png'),
    'Матч! Боец': require('../assets/channels/Матч! Боец.png'),
    'Матч! Игра HD': require('../assets/channels/Матч! Игра HD.png'),
    'Матч! Игра': require('../assets/channels/Матч! Игра.png'),
    'Матч! Наш спорт': require('../assets/channels/Матч! Наш спорт.png'),
    'Матч! Планета': require('../assets/channels/Матч! Планета.png'),
    'Матч! Футбол 1 HD': require('../assets/channels/Матч! Футбол 1 HD.png'),
    'Матч! Футбол 1': require('../assets/channels/Матч! Футбол 1.png'),
    'Матч! Футбол 2 HD': require('../assets/channels/Матч! Футбол 2 HD.png'),
    'Матч! Футбол 2': require('../assets/channels/Матч! Футбол 2.png'),
    'Матч! Футбол 3 HD': require('../assets/channels/Матч! Футбол 3 HD.png'),
    'Матч! Футбол 3': require('../assets/channels/Матч! Футбол 3.png'),
    'Мир': require('../assets/channels/Мир.png'),
    'Много ТВ': require('../assets/channels/Много ТВ.png'),
    'Москва 24': require('../assets/channels/Москва 24.png'),
    'Моя Планета': require('../assets/channels/Моя Планета.png'),
    'Музыка': require('../assets/channels/Музыка.png'),
    'НТВ HD': require('../assets/channels/НТВ HD.png'),
    'НТВ': require('../assets/channels/НТВ.png'),
    'Надежда': require('../assets/channels/Надежда.png'),
    'Наука 2.0': require('../assets/channels/Наука 2.0.png'),
    'Наш футбол HD': require('../assets/channels/Наш футбол HD.png'),
    'Наш футбол': require('../assets/channels/Наш футбол.png'),
    'Наше новое кино': require('../assets/channels/Наше новое кино.png'),
    'Ностальгия': require('../assets/channels/Ностальгия.png'),
    'ОТР': require('../assets/channels/ОТР.png'),
    'Охота и Рыбалка': require('../assets/channels/Охота и Рыбалка.png'),
    'Первый HD': require('../assets/channels/Первый HD.png'),
    'Первый канал': require('../assets/channels/Первый канал.png'),
    'Первый образовательный': require('../assets/channels/Первый образовательный.png'),
    'Пятница': require('../assets/channels/Пятница.png'),
    'Пятый Канал': require('../assets/channels/Пятый Канал.png'),
    'РБК-ТВ': require('../assets/channels/РБК-ТВ.png'),
    'РЕН ТВ': require('../assets/channels/РЕН ТВ.png'),
    'РОДНОЕ КИНО': require('../assets/channels/РОДНОЕ КИНО.png'),
    'Россия HD': require('../assets/channels/Россия HD.png'),
    'Россия-24': require('../assets/channels/Россия-24.png'),
    'Россия-Культура': require('../assets/channels/Россия-Культура.png'),
    'Русская Ночь': require('../assets/channels/Русская Ночь.png'),
    'Русский Иллюзион': require('../assets/channels/Русский Иллюзион.png'),
    'Русский Экстрим': require('../assets/channels/Русский Экстрим.png'),
    'СТС Love': require('../assets/channels/СТС Love.png'),
    'СТС': require('../assets/channels/СТС.png'),
    'Сов. Секретно': require('../assets/channels/Сов. Секретно.png'),
    'ТВ3': require('../assets/channels/ТВ3.png'),
    'ТВЦ': require('../assets/channels/ТВЦ.png'),
    'ТНВ-Планета': require('../assets/channels/ТНВ-Планета.png'),
    'ТНТ': require('../assets/channels/ТНТ.png'),
    'ТНТ4': require('../assets/channels/ТНТ4.png'),
    'Телеканал «Россия»': require('../assets/channels/Телеканал «Россия».png'),
    'Телеканал Да Винчи': require('../assets/channels/Телеканал Да Винчи.png'),
    'Телеканал Звезда': require('../assets/channels/Телеканал Звезда.png'),
    'Телеканал КХЛ HD': require('../assets/channels/Телеканал КХЛ HD.png'),
    'Че': require('../assets/channels/Че.png'),
    'Эгоист': require('../assets/channels/Эгоист.png'),
    'Ю ТВ': require('../assets/channels/Ю ТВ.png'),
    'Ար': require('../assets/channels/Ար.png'),
    'Արմենիա Tv HD': require('../assets/channels/Արմենիա Tv HD.png'),
    'Արմենիա Tv': require('../assets/channels/Արմենիա Tv.png'),
    'Արմնյուզ': require('../assets/channels/Արմնյուզ.png'),
    'Դար 21': require('../assets/channels/Դար 21.png'),
    'Երկիր մեդիա': require('../assets/channels/Երկիր մեդիա.png'),
    'Կենտրոն': require('../assets/channels/Կենտրոն.png'),
    'Հ1': require('../assets/channels/Հ1.png'),
    'Հ2': require('../assets/channels/Հ2.png'),
    'Հ3': require('../assets/channels/Հ3.png'),
    'Շանթ': require('../assets/channels/Շանթ.png'),
    'Շողակաթ': require('../assets/channels/Շողակաթ.png')
};

export default ChannelIcons;
